fragment PheWASCatalogSummary on Disease {
  phewasCatalogSummary: evidences(
    ensemblIds: [$ensgId]
    enableIndirect: true
    datasourceIds: ["phewas_catalog"]
    size: 0
  ) {
    count
  }
}
