query PathwaysSectionQuery($ensgId: String!, $efoId: String!) {
  evidence(ensgId: $ensgId, efoId: $efoId) {
    details {
      pathways {
        rowsPathways {
          disease {
            id
            name
          }
          activity
          pathway {
            id
            name
          }
          # TODO: add several other fields
        }
      }
    }
  }
}
