query GenomicsEnglandQuery($ensemblId: String!, $efoId: String!) {
  disease(efoId: $efoId) {
    id
    evidences(
      ensemblIds: [$ensemblId]
      enableIndirect: true
      datasourceIds: ["genomics_england"]
    ) {
      rows {
        disease {
          id
          name
        }
        target {
          approvedSymbol
        }
        diseaseFromSource
        cohortPhenotypes
        confidence
        allelicRequirements
        studyOverview
        studyId
        confidence
        literature
      }
    }
  }
}
