query RelatedDiseasesExpansionQuery($pageEfoId: String!, $otherEfoId: String!) {
  disease(efoId: $pageEfoId) {
    id
    details {
      relatedDiseases {
        expanded(otherEfoId: $otherEfoId) {
          target {
            id
            symbol
          }
          associationScoreA
          associationScoreB
        }
      }
    }
  }
}
