query DrugsSectionQuery($ensgId: String!, $efoId: String!) {
  evidence(ensgId: $ensgId, efoId: $efoId) {
    details {
      drugs {
        rows {
          disease {
            id
            name
          }
          target {
            id
            symbol
          }
          drug {
            id
            name
            type
            activity
          }
          clinicalTrial {
            phase
            status
            sourceUrl
            sourceName
          }
          mechanismOfAction {
            name
            sourceName
            sourceUrl
          }
        }
      }
    }
  }
}
