query GeneticSectionQuery($ensgId: String!, $efoId: String!) {
  evidence(ensgId: $ensgId, efoId: $efoId) {
    details {
      otGenetics {
        rows {
          disease{
            id
            name
          }
          reportedTrait{
            name
            url
          }
          publications{
            authors
            year
            url
            pmId
          }
          variant{
            id
            url
          }
          pval{
            mantissa
            exponent
            value
          }
          genePrioritisationScore
          source{
            name
            url
          }
        }
      }
      uniProt {
        rows {
          disease {
            id
            name
          }
          rsId
          vepConsequence
          source {
            name
            url
          }
          pmIds
        }
      }
      uniProtLiterature {
        rows {
          disease {
            id
            name
          }
          source {
            name
            url
          }
          pmIds
        }
      }
      eva {
        rows {
          disease {
            id
            name
          }
          clinVarId
          rsId
          vepConsequence
          clinicalSignificance
          pmId
        }
      }
      genomicsEngland {
        rows {
          disease {
            id
            name
          }
          panel {
            id
            url
          }
          source {
            url
            name
          }
        }
      }
      gene2Phenotype {
        rows {
          disease {
            id
            name
          }
          panelsUrl
          pmId
        }
      }
    }
  }
}
