query TargetPageQuery($ensgId: String!) {
  target(ensemblId: $ensgId) {
    id
    approvedSymbol
    approvedName
    functionDescriptions
    proteinIds {
      id
      source
    }
    dbXrefs {
      id
      source
    }
  }
}
