query AdverseEventsSectionQuery($chemblId: String!) {
  drug(chemblId: $chemblId) {
    id
    details{
      adverseEvents{
        rows{
          event
          count
          llr
        }
      }
    }
  }
}
