query DifferentialExpressionSectionQuery($ensgId: String!, $efoId: String!) {
  evidence(ensgId: $ensgId, efoId: $efoId) {
    details {
      differentialExpression {
        rows {
          disease {
            id
            name
          }
          tissue {
            id
            name
          }
          activity {
            url
            name
          }
          comparison
          evidenceSource
          log2FoldChange
          percentileRank
          pval
          experiment {
            url
            name
          }
        }
      }
    }
  }
}
