query ExpressionAtlasQuery($ensemblId: String!, $efoId: String!, $size: Int!) {
  disease(efoId: $efoId) {
    id
    evidences(
      ensemblIds: [$ensemblId]
      enableIndirect: true
      datasourceIds: ["expression_atlas"]
      size: $size
    ) {
      rows {
        disease {
          id
          name
        }
        diseaseFromSource
        contrast
        confidence
        studyOverview
        log2FoldChangeValue
        resourceScore
        log2FoldChangePercentileRank
        studyId
      }
    }
  }
}
