query RelatedDiseasesQuery(
    $efoId: String!
    $index: Int! = 0
    $size: Int! = 10
  ) {
    disease(efoId: $efoId) {
      id
      relatedDiseases(page: { index: $index, size: $size }) {
        count
        maxCountAOrB
        rows {
          id
          countA
          countB
          countAOrB
          countAAndB
          score
          B {
            id
            name
          }
        }
      }
    }
  }