query OntologySectionQuery($efoId: String!) {
  disease(efoId: $efoId) {
    id
    details {
      ontology {
        nodes {
          id
          name
          parentIds
        }
      }
    }
  }
}
