query SysBioSectionQuery($ensgId: String!, $efoId: String!) {
  evidence(ensgId: $ensgId, efoId: $efoId) {
    details {
      sysBio {
        rows {
          disease {
            id
            name
          }
          geneSet
          method
          pmId
        }
      }
    }
  }
}
