query knownDrugsSectionQuery(
  $chemblId: String!
  $index: Int! = 0
  $size: Int! = 10
  $freeTextQuery: String! = ""
) {
  drug(chemblId: $chemblId) {
    id
    knownDrugs(
      page: { index: $index, size: $size }
      freeTextQuery: $freeTextQuery
    ) {
      count
      rows {
        phase
        status
        ctIds

        disease {
          id
          name
        }

        target {
          id
          approvedName
          approvedSymbol
        }
      }
    }
  }
}
