query knownDrugsSectionQuery(
  $chemblId: String!
  $index: Int! = 0
  $size: Int! = 100
  $freeTextQuery: String! = ""
) {
  drug(chemblId: $chemblId) {
    id
    knownDrugs(freeTextQuery: $freeTextQuery, size: $size, cursor: $cursor) {
      count
      cursor
      rows {
        phase
        status
        urls {
          name
          url
        }

        disease {
          id
          name
        }

        target {
          id
          approvedName
          approvedSymbol
        }
      }
    }
  }
}
