query SearchQuery($queryString: String!) {
  search(queryString: $queryString) {
    topHit {
      id
      name
    }
    targets {
      id
      approvedSymbol
    }
    drugs {
      id
      name
    }
  }
}
