query SearchQuery($queryString: String!) {
  search(queryString: $queryString) {
    topHit {
      __typename
      ... on Target {
        id
        approvedSymbol
        approvedName
        proteinAnnotations {
          functions
        }
      }
      ... on Drug {
        id
        name
      }
      ... on Disease {
        id
        name
        description
      }
    }
    targets {
      id
      approvedSymbol
      approvedName
    }
    diseases {
      id
      name
    }
    drugs {
      id
      name
    }
  }
}
