query GenomicsEnglandSectionQuery($ensgId: String!, $efoId: String!) {
  evidence(ensgId: $ensgId, efoId: $efoId) {
    details {
      genomicsEngland {
        rows {
          disease {
            id
            name
          }
          panel {
            id
            url
          }
          source {
            url
            name
          }
        }
      }
    }
  }
}
