query knownDrugsSectionQuery($efoId: String!, $index: Int! = 0, $size: Int! = 10) {
  disease(efoId: $efoId) {
    id
    name
    description
    knownDrugs(page:{index: $index, size: $size}) {
      count
      rows {
        disease {
          name
        }
        phase
        status
        ctIds
        drug {
          name
        }
        drugType
        mechanismOfAction
        activity
      }
    }
  }
}


# query KnownDrugsSectionQuery($efoId: String!) {
#   disease(efoId: $efoId) {
#     id
#     details {
#       drugs {
#         rows {
#           disease {
#             id
#             name
#           }
#           target {
#             id
#             symbol
#           }
#           drug {
#             id
#             name
#             type
#             activity
#           }
#           clinicalTrial {
#             phase
#             status
#             sourceUrl
#             sourceName
#           }
#           mechanismOfAction {
#             name
#             sourceName
#             sourceUrl
#           }
#         }
#       }
#     }
#   }
# }
