query knownDrugsSectionQuery(
  $efoId: String!
  $index: Int! = 0
  $size: Int! = 10
  $freeTextQuery: String! = ""
) {
  disease(efoId: $efoId) {
    id
    knownDrugs(
      page: { index: $index, size: $size }
      freeTextQuery: $freeTextQuery
    ) {
      count
      rows {
        phase
        status
        urls {
          name
          url
        }

        # disease {
        #   id
        #   name
        # }

        drug {
          id
          name
        }
        drugType
        mechanismOfAction
        activity

        target {
          id
          approvedName
          approvedSymbol
        }
      }
    }
  }
}
