query SomaticSectionQuery($ensgId: String!, $efoId: String!) {
  evidence(ensgId: $ensgId, efoId: $efoId) {
    details {
      uniProtSomatic {
        rows {
          disease {
            id
            name
          }
          vepConsequence
          source {
            name
            url
          }
          pmIds
        }
      }
      evaSomatic {
        rows {
          disease {
            id
            name
          }
          clinVarId
          rsId
          vepConsequence
          clinicalSignificance
          pmId
        }
      }
      cancerGeneCensus {
        rows {
          disease {
            id
            name
          }
          mutationType
          inheritancePattern
          samplesWithMutationTypeCount
          mutatedSamplesCount
          source {
            url
            name
          }
          pmIds
        }
      }
      intogen {
        rows {
          disease {
            id
            name
          }
          activity
          inheritancePattern
          source {
            url
            name
          }
          pmId
          pval
          cohort{
            name
            description
          }
          analysisMethods
          mutationMetrics{
            value
            total
          }
        }
      }
    }
  }
}
