import React from 'react';
import Link from '../../../components/Link';

const Description = ({ symbol, name }) => (
  <>
    Interim data from dual-knockout screens generated by the{' '}
    <Link external to="http://home.opentargets.org/OTAR2062">
      OTAR2-062 ENCORE project
    </Link>
    , associating <strong>{symbol}</strong> and <strong>{name}</strong>. Source:{' '}
    <Link external to="http://home.opentargets.org/">
      Open Targets
    </Link>
  </>
);

export default Description;
