import React from 'react';
import Link from '../../../components/Link';

const Description = ({ symbol, name }) => (
  <>
    Data generated by{' '}
    <Link external to="http://home.opentargets.org/OTAR2062">
      select primary OTAR projects
    </Link>{' '}
    that have undergone orthogonal experimental validation, associating{' '}
    <strong>{symbol}</strong> and <strong>{name}</strong>. Source:{' '}
    <Link external to="http://home.opentargets.org/">
      Open Targets
    </Link>
  </>
);

export default Description;
