query SearchQuery($queryString: String!) {
  topHit: search(
    queryString: $queryString
    entityNames: ["target"]
    page: { index: 0, size: 1 }
  ) {
    hits {
      id
      entity
      object {
        ... on Target {
          id
          approvedSymbol
          approvedName
          proteinAnnotations {
            id
            functions
          }
        }
      }
    }
  }
  targets: search(
    queryString: $queryString
    entityNames: ["target"]
    page: { index: 0, size: 3 }
  ) {
    hits {
      id
      entity
      object {
        ... on Target {
          id
          approvedSymbol
          approvedName
        }
      }
    }
  }
}
