fragment OpenTargetsGeneticsSummaryFragment on Disease {
  openTargetsGenetics: evidences(
    ensemblIds: [$ensgId]
    enableIndirect: true
    datasourceIds: ["ot_genetics_portal"]
    size: 0
  ) {
    count
  }
}
