query OpenTargetsGeneticsQuery(
  $ensemblId: String!
  $efoId: String!
  $size: Int!
) {
  disease(efoId: $efoId) {
    id
    evidences(
      ensemblIds: [$ensemblId]
      enableIndirect: true
      size: $size
      datasourceIds: ["ot_genetics_portal"]
    ) {
      rows {
        id
        disease {
          id
          name
        }
        diseaseFromSource
        studyId
        studySampleSize
        variantId
        variantRsId
        literature
        publicationYear
        publicationFirstAuthor
        pValueExponent
        pValueMantissa
        oddsRatio
        confidenceIntervalLower
        confidenceIntervalUpper
        variantFunctionalConsequence {
          id
          label
        }
        resourceScore
      }
    }
  }
}
