fragment evidenceGeneticFragment on EvidenceSummaries {
  gwasCatalog {
    variantCount
    sources {
      name
      url
    }
  }
  uniProt {
    variantCount
    sources {
      name
      url
    }
  }
  uniProtLiterature {
    hasVariants
    sources {
      name
      url
    }
  }
  eva {
    variantCount
    sources {
      name
      url
    }
  }
  genomicsEngland {
    hasPanel
    sources {
      name
      url
    }
  }
  gene2Phenotype {
    hasPanel
    sources {
      name
      url
    }
  }
}
