const dataSources = [
  { id: 'ot_genetics_portal', label: 'OT Genetics Portal', isPrivate: false },
  { id: 'phewas_catalog', label: 'PheWAS Catalog', isPrivate: false },
  { id: 'eva', label: 'ClinVar', isPrivate: false },
  { id: 'uniprot', label: 'UniProt curated variants', isPrivate: false },
  { id: 'genomics_england', label: 'GEL PanelApp', isPrivate: false },
  { id: 'gene2phenotype', label: 'Gene2phenotype', isPrivate: false },
  { id: 'uniprot_literature', label: 'UniProt literature', isPrivate: false },
  { id: 'clingen', label: 'Clingen', isPrivate: false },
  { id: 'cancer_gene_census', label: 'Cancer Gene Census', isPrivate: false },
  { id: 'intogen', label: 'IntOGen', isPrivate: false },
  { id: 'eva_somatic', label: 'ClinVar (somatic)', isPrivate: false },
  { id: 'uniprot_somatic', label: 'UniProt (somatic)', isPrivate: false },
  { id: 'chembl', label: 'ChEMBL', isPrivate: false },
  { id: 'crispr', label: 'Project Score', isPrivate: false },
  { id: 'slapenrich', label: 'SLAPenrich', isPrivate: false },
  { id: 'progeny', label: 'PROGENy', isPrivate: false },
  { id: 'reactome', label: 'Reactome', isPrivate: false },
  { id: 'sysbio', label: 'Gene signatures', isPrivate: false },
  { id: 'europepmc', label: 'Europe PMC', isPrivate: false },
  { id: 'expression_atlas', label: 'Expression Atlas', isPrivate: false },
  { id: 'phenodigm', label: 'PhenoDigm', isPrivate: false },
  {
    id: 'uniprot_variants',
    label: 'UniProt curated variants',
    isPrivate: false,
  },
  { id: 'orphanet', label: 'Orphanet', isPrivate: false },
  { id: 'ot_crispr', label: 'OTAR CRISPR', isPrivate: true },
];

export default dataSources;
