query drugApprovalWithdrawnWarningData {
  drug(chemblId: "CHEMBL118") {
    name
    id
    isApproved
    hasBeenWithdrawn
    blackBoxWarning
    drugWarnings {
      warningType
      description
      toxicityClass
      meddraSocCode
      year
      references {
        id
        source
        url
      }
    }
  }
}
