query SearchPageQuery($queryString: String!) {
  search(queryString: $queryString, page: { index: 0, size: 10 }) {
    targets {
      id
      approvedSymbol
      approvedName
      bioType
      proteinAnnotations {
        id
        functions
        accessions
      }
      associationsOnTheFly(page: { index: 0, size: 5 }) {
        rows {
          id
        }
      }
    }
    diseases {
      id
      name
      description
    }
    drugs {
      id
      name
    }
  }
}
