query TopHit($queryString: String!) {
  search(queryString: $queryString, page: { index: 0, size: 1 }) {
    hits {
      id
      object {
        ... on Target {
          id
          approvedSymbol
          approvedName
          bioType
          proteinAnnotations {
            functions
            accessions
          }
          associationsOnTheFly(page: { index: 0, size: 5 }) {
            rows {
              id
            }
          }
        }
        ... on Disease {
          id
          name
          description
          associationsOnTheFly(page: { index: 0, size: 5 }) {
            rows {
              id
            }
          }
          therapeuticAreas {
            id
            name
          }
        }
        ... on Drug {
          id
          name
        }
      }
    }
  }
}
